name: coolify
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/coolify.webp
  index: /
  is_uncontrolled: false
  port_map: "3500"
  scheme: http
  store_app_id: coolify
  title:
    custom: ""
    en_us: coolify

services:
  coolify:
    cpu_shares: 90
    command: []
    container_name: coolify
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1073741824
        reservations:
          devices: []
    environment:
      - APP_DEBUG=false
      - APP_ENV=production
    image: ghcr.io/coollabsio/coolify:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/coolify.webp
    ports:
      - target: 3000
        published: "3500"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/coolify/data
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    networks:
      - coolify
    privileged: false
  traefik:
    cpu_shares: 90
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8000
      - --api.dashboard=true
      - --api.insecure=true
    container_name: coolify-traefik
    deploy:
      resources:
        limits:
          memory: 8283295744
        reservations:
          devices: []
    image: traefik:v2.11
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/coolify.webp
    ports:
      - target: 8000         # App traffic
        published: "8000"
        protocol: tcp
      - target: 8080         # Traefik dashboard
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    environment: []
    networks:
      - coolify
    privileged: false
networks:
  coolify:
    name: coolify_coolify
    driver: bridge