name: 1snakeaid-api-dev

x-casaos:
  author: self
  category: self
  title:
    custom: SnakeAid API Dev
    en_us: SnakeAid API Dev
  hostname: ""
  icon: https://thumbs.dreamstime.com/b/minimalist-viper-logo-design-snake-silhouette-sleek-modern-black-white-featuring-s-head-integrated-stylized-v-362003031.jpg
  index: /index.html
  is_uncontrolled: false
  port_map: "5111"
  scheme: http
  store_app_id: 1snakeaid-api-dev

services:
  1snakeaid-api-dev:
    cpu_shares: 90
    command: []
    container_name: 1snakeaid-api-dev
    depends_on:
      rabbitmq:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 8283287552
        reservations:
          devices: []
    environment:
      - RabbitMq__Host=rabbitmq
      - FIREBASE_CREDENTIAL_PATH=/app/secrets/firebase-service-account.json
    image: thekhiem7/snakeaid-api:dev
    labels:
      icon: https://thumbs.dreamstime.com/b/minimalist-viper-logo-design-snake-silhouette-sleek-modern-black-white-featuring-s-head-integrated-stylized-v-362003031.jpg
    ports:
      - target: 8080
        published: "5111"
        protocol: tcp
    pull_policy: always
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/SnakeAid/secrets/firebase-service-account.json
        target: /app/secrets/firebase-service-account.json
        read_only: true
    devices: []
    cap_add: []
    networks:
      - snakeaid-dev-network
    privileged: false
  rabbitmq:
    cpu_shares: 90
    command: []
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          memory: 8283287552
        reservations:
          devices: []
    environment:
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_USER=admin
    image: rabbitmq:management
    labels:
      icon: https://thumbs.dreamstime.com/b/minimalist-viper-logo-design-snake-silhouette-sleek-modern-black-white-featuring-s-head-integrated-stylized-v-362003031.jpg
    ports:
      - target: 5672
        published: "5672"
        protocol: tcp
      - target: 15672
        published: "15672"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/RabbitMQ/data
        target: /var/lib/rabbitmq
    devices: []
    cap_add: []
    networks:
      - snakeaid-dev-network
    privileged: false

networks:
  snakeaid-dev-network:
    name: snakeaid-dev-network
    driver: bridge