name: snakeaid-api-dev

x-casaos:
  author: self
  category: self
  title:
    custom: SnakeAid API Dev
    en_us: SnakeAid API Dev
  hostname: ""
  icon: https://thumbs.dreamstime.com/b/minimalist-viper-logo-design-snake-silhouette-sleek-modern-black-white-featuring-s-head-integrated-stylized-v-362003031.jpg
  index: /index.html
  is_uncontrolled: false
  port_map: "5111"
  scheme: http
  store_app_id: snakeaid-api-dev

services:
  snakeaid-api-dev:
    cpu_shares: 90
    command: []
    container_name: snakeaid-api-dev
    deploy:
      resources:
        limits:
          memory: 8283295744
        reservations:
          devices: []
    image: thekhiem7/snakeaid-api:dev
    labels:
      icon: https://thumbs.dreamstime.com/b/minimalist-viper-logo-design-snake-silhouette-sleek-modern-black-white-featuring-s-head-integrated-stylized-v-362003031.jpg
    ports:
      - target: 8080
        published: "5111"
        protocol: tcp
    pull_policy: always
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    environment:
