name: snakeaid-api

x-casaos:
  author: self
  category: self
  title:
    custom: SnakeAid API
    en_us: snakeaid-api
  hostname: ""
  icon: https://avatars.githubusercontent.com/u/241086090?s=200&v=4
  index: /index.html
  is_uncontrolled: false
  port_map: "5110"
  scheme: http
  store_app_id: snakeaid-api

services:
  snakeaid-api:
    cpu_shares: 90
    command: []
    container_name: snakeaid-api
    deploy:
      resources:
        limits:
          memory: 8283295744
        reservations:
          devices: []
    image: thekhiem7/snakeaid-api:latest
    labels:
      icon: https://avatars.githubusercontent.com/u/241086090?s=200&v=4
    ports:
      - target: 8080
        published: "5110"
        protocol: tcp
    pull_policy: always
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    environment: