services:
  snakeaid-api:
    container_name: snakeaid-api
    image: thekhiem7/snakeaid-api:latest
    pull_policy: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/swagger/index.html || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    environment: