version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "1000:1000"
    volumes:
      - /DATA:/srv
      - /DATA/filebrowser/database:/database
      - /DATA/filebrowser/config:/config
    ports:
      - 8088:80
    restart: unless-stopped